"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Download, Share2, Copy, Mail, Check, Loader2, Bookmark } from "lucide-react";
import { saveRate } from "./saved-rates";
import type { CreatorProfile, PricingResult, FitScoreResult, ParsedBrief } from "@/lib/types";

interface ShareActionsProps {
  profile: CreatorProfile;
  brief: ParsedBrief | Omit<ParsedBrief, "id">;
  fitScore: FitScoreResult;
  pricing: PricingResult;
}

export function ShareActions({ profile, brief, fitScore, pricing }: ShareActionsProps) {
  const [downloading, setDownloading] = useState(false);
  const [copied, setCopied] = useState(false);
  const [saved, setSaved] = useState(false);
  const [emailDialogOpen, setEmailDialogOpen] = useState(false);
  const [email, setEmail] = useState("");
  const [message, setMessage] = useState("");

  const isMobile = typeof window !== "undefined" &&
    /iPhone|iPad|iPod|Android/i.test(navigator.userAgent);

  const downloadPDF = async () => {
    setDownloading(true);
    try {
      const response = await fetch("/api/generate-pdf", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ profile, brief, fitScore, pricing }),
      });

      if (!response.ok) throw new Error("Failed to generate PDF");

      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `ratecard-${profile.handle}-${Date.now()}.pdf`;
      document.body.appendChild(a);
      a.click();
      a.remove();
      window.URL.revokeObjectURL(url);
    } catch (err) {
      console.error("Download failed:", err);
    } finally {
      setDownloading(false);
    }
  };

  const copyToClipboard = async () => {
    const currencySymbol = pricing.currencySymbol || "$";
    const text = `Rate Card for ${brief.brand.name}

Creator: ${profile.displayName} (@${profile.handle})
Content: ${brief.content.quantity}x ${brief.content.format} on ${brief.content.platform}
Usage: ${brief.usageRights.durationDays === 0 ? "Organic only" : `${brief.usageRights.durationDays} days paid usage`}

Rate: ${currencySymbol}${pricing.totalPrice.toLocaleString()}
Valid for: ${pricing.validDays} days

Generated by RateCard.AI`;

    await navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const shareNative = async () => {
    if (!navigator.share) return;

    try {
      const response = await fetch("/api/generate-pdf", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ profile, brief, fitScore, pricing }),
      });

      if (response.ok) {
        const blob = await response.blob();
        const file = new File([blob], `ratecard-${profile.handle}.pdf`, { type: "application/pdf" });

        await navigator.share({
          title: `Rate Card - ${profile.displayName}`,
          text: `My rate for ${brief.content.quantity}x ${brief.content.format}: ${pricing.currencySymbol || "$"}${pricing.totalPrice.toLocaleString()}`,
          files: [file],
        });
      }
    } catch {
      // Fallback to text share if file sharing fails
      try {
        await navigator.share({
          title: `Rate Card - ${profile.displayName}`,
          text: `My rate for ${brief.content.quantity}x ${brief.content.format}: ${pricing.currencySymbol || "$"}${pricing.totalPrice.toLocaleString()}`,
        });
      } catch {
        // User cancelled or share not supported
      }
    }
  };

  const openEmailClient = () => {
    const subject = encodeURIComponent(`Rate Card from ${profile.displayName}`);
    const body = encodeURIComponent(`Hi,

Please find my rate card for the ${brief.brand.name} campaign.

Rate: ${pricing.currencySymbol || "$"}${pricing.totalPrice.toLocaleString()}
Content: ${brief.content.quantity}x ${brief.content.format} on ${brief.content.platform}

${message ? `${message}\n\n` : ""}Best,
${profile.displayName}

---
Generated by RateCard.AI`);

    window.open(`mailto:${email}?subject=${subject}&body=${body}`);
    setEmailDialogOpen(false);
  };

  const handleSave = () => {
    saveRate({
      name: `${brief.content.format} on ${brief.content.platform}`,
      platform: brief.content.platform,
      format: brief.content.format,
      usageRights: brief.usageRights.durationDays > 0
        ? `${brief.usageRights.durationDays}-day usage`
        : "Organic only",
      price: pricing.totalPrice,
    });
    setSaved(true);
  };

  // Mobile-first layout with native share
  const hasNativeShare = typeof navigator !== "undefined" && "share" in navigator;
  if (isMobile && hasNativeShare) {
    return (
      <div className="flex gap-2">
        <Button onClick={shareNative} className="flex-1">
          <Share2 className="mr-2 h-4 w-4" />
          Share Rate Card
        </Button>

        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button variant="outline" size="icon">
              <Download className="h-4 w-4" />
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end">
            <DropdownMenuItem onClick={downloadPDF} disabled={downloading}>
              {downloading ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Download className="mr-2 h-4 w-4" />}
              Download PDF
            </DropdownMenuItem>
            <DropdownMenuItem onClick={copyToClipboard}>
              {copied ? <Check className="mr-2 h-4 w-4" /> : <Copy className="mr-2 h-4 w-4" />}
              Copy as Text
            </DropdownMenuItem>
            <DropdownMenuSeparator />
            <DropdownMenuItem onClick={() => setEmailDialogOpen(true)}>
              <Mail className="mr-2 h-4 w-4" />
              Email to Brand
            </DropdownMenuItem>
            <DropdownMenuSeparator />
            <DropdownMenuItem onClick={handleSave} disabled={saved}>
              {saved ? <Check className="mr-2 h-4 w-4 text-emerald-500" /> : <Bookmark className="mr-2 h-4 w-4" />}
              {saved ? "Saved" : "Save Rate"}
            </DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>

        <Dialog open={emailDialogOpen} onOpenChange={setEmailDialogOpen}>
          <DialogContent>
            <DialogHeader>
              <DialogTitle>Email Rate Card</DialogTitle>
              <DialogDescription>
                Send your rate card directly to the brand.
              </DialogDescription>
            </DialogHeader>
            <div className="space-y-4 pt-4">
              <div className="space-y-2">
                <Label htmlFor="email-mobile">Recipient Email</Label>
                <Input
                  id="email-mobile"
                  type="email"
                  placeholder="brand@company.com"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="message-mobile">Personal Message (optional)</Label>
                <Textarea
                  id="message-mobile"
                  placeholder="Looking forward to working together!"
                  value={message}
                  onChange={(e) => setMessage(e.target.value)}
                  rows={3}
                />
              </div>
              <Button onClick={openEmailClient} className="w-full" disabled={!email}>
                <Mail className="mr-2 h-4 w-4" />
                Open Email App
              </Button>
            </div>
          </DialogContent>
        </Dialog>
      </div>
    );
  }

  // Desktop layout
  return (
    <>
      <div className="flex gap-2">
        <Button onClick={downloadPDF} disabled={downloading} className="flex-1">
          {downloading ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Download className="mr-2 h-4 w-4" />}
          Download PDF
        </Button>

        <Button
          variant="outline"
          onClick={handleSave}
          disabled={saved}
        >
          {saved ? (
            <>
              <Check className="mr-2 h-4 w-4 text-emerald-500" />
              Saved
            </>
          ) : (
            <>
              <Bookmark className="mr-2 h-4 w-4" />
              Save Rate
            </>
          )}
        </Button>

        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button variant="outline">
              <Share2 className="mr-2 h-4 w-4" />
              Share
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end">
            <DropdownMenuItem onClick={copyToClipboard}>
              {copied ? <Check className="mr-2 h-4 w-4" /> : <Copy className="mr-2 h-4 w-4" />}
              Copy as Text
            </DropdownMenuItem>
            <DropdownMenuItem onClick={() => setEmailDialogOpen(true)}>
              <Mail className="mr-2 h-4 w-4" />
              Email to Brand
            </DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      </div>

      <Dialog open={emailDialogOpen} onOpenChange={setEmailDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Email Rate Card</DialogTitle>
            <DialogDescription>
              Send your rate card directly to the brand.
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4 pt-4">
            <div className="space-y-2">
              <Label htmlFor="email-desktop">Recipient Email</Label>
              <Input
                id="email-desktop"
                type="email"
                placeholder="brand@company.com"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="message-desktop">Personal Message (optional)</Label>
              <Textarea
                id="message-desktop"
                placeholder="Looking forward to working together!"
                value={message}
                onChange={(e) => setMessage(e.target.value)}
                rows={3}
              />
            </div>
            <Button onClick={openEmailClient} className="w-full" disabled={!email}>
              <Mail className="mr-2 h-4 w-4" />
              Open Email App
            </Button>
          </div>
        </DialogContent>
      </Dialog>
    </>
  );
}
